name: flowdelivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.3.1
  flutter_web_plugins:
    sdk: flutter
  go_router: ^17.2.3
  intl: ^0.20.2
  supabase_flutter: ^2.12.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Variable.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Variable.ttf
